// AUTH
export const AUTH_SIGNIN = "AUTH_SIGNIN";
export const AUTH_SIGNIN_SUCCESS = "AUTH_SIGNIN_SUCCESS";
export const AUTH_SIGNIN_FAILIURE_ON_PASSWORD
  = "AUTH_SIGNIN_FAILIURE_ON_PASSWORD";
export const AUTH_SIGNIN_FAILIURE_ON_NONEXIST
  = "AUTH_SIGNIN_FAILIURE_ON_NONEXIST";

export const AUTH_GET_PROFILE = "AUTH_GET_PROFILE";
export const AUTH_GET_PROFILE_SUCCESS = "AUTH_GET_PROFILE_SUCCESS";
export const AUTH_GET_PROFILE_FAILURE = "AUTH_GET_PROFILE_FAILURE";

export const AUTH_SIGNOUT = "AUTH_SIGNOUT";

// USER
export const USER_SIGNUP = "USER_SIGNUP";
export const USER_UPDATE = "USER_UPDATE";
export const USER_WITHDRAW = "USER_WITHDRAW";

// POST
export const POST_UPLOAD = "POST_UPLOAD";
export const POST_UPLOAD_SUCCESS = "POST_UPLOAD_SUCCESS";
export const POST_UPLOAD_FAIL = "POST_UPLOAD_FAIL";

export const POST_UPDATE = "POST_UPDATE";
export const POST_UPDATE_SUCCESS = "POST_UPDATE_SUCCESS";
export const POST_UPDATE_FAIL = "POST_UPDATE_FAIL";

export const POST_READ = "POST_READ";
export const POST_READ_SUCCESS = "POST_READ_SUCCESS";
export const POST_READ_FAIL = "POST_READ_FAIL";

export const POST_DELETE = "POST_DELETE";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_DELETE_FAIL = "POST_DELETE_FAIL";
