// USER
export const USER_SIGNIN = "USER_SIGNIN";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const USER_GET_STATUS = "USER_GET_STATUS";
export const USER_GET_STATUS_SUCCESS = "USER_GET_STATUS_SUCCESS";
export const USER_GET_STATUS_FAIL = "USER_GET_STATUS_FAIL";

export const USER_SIGNOUT = "USER_SIGNOUT";

export const USER_SIGNUP = "USER_SIGNUP";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

export const USER_UPDATE = "USER_UPDATE";
export const USER_WITHDRAW = "USER_WITHDRAW";

// POST
export const POST_UPLOAD = "POST_UPLOAD";
export const POST_UPLOAD_SUCCESS = "POST_UPLOAD_SUCCESS";
export const POST_UPLOAD_FAIL = "POST_UPLOAD_FAIL";

export const POST_LIST = "POST_LIST";
export const POST_LIST_SUCCESS = "POST_LIST_SUCCESS";

export const POST_UPDATE = "POST_UPDATE";
export const POST_UPDATE_SUCCESS = "POST_UPDATE_SUCCESS";
export const POST_UPDATE_FAIL = "POST_UPDATE_FAIL";

export const POST_READ = "POST_READ";
export const POST_READ_SUCCESS = "POST_READ_SUCCESS";
export const POST_READ_FAIL = "POST_READ_FAIL";

export const POST_DELETE = "POST_DELETE";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_DELETE_FAIL = "POST_DELETE_FAIL";
